### ISSUE TITLE
[CSP] violation when loading add-on details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1469] opened 2016-01-21 11:45 UTC
Relates to #995 

**Pre-requisite:  `network.prefetch-next` must be `true` in about:config**

Steps to reproduce:
1. Load AMO-stage page https://addons.allizom.org/en-US/
2. Load any add-on details page (i.e. https://addons.allizom.org/en-US/firefox/addon/firebug/?src=hp-dl-mostpopular) with the console opened (and Security tab checked)
3. Observe the console

Expected results:
There are no issues CSP related.

Actual results:
There is a CSP violation.

Notes/Issues:
Verified on FF43(Win 7). Reproducible in AMO-stage and AMO-dev.
Screenshot for this issue: 
![desk](https://cloud.githubusercontent.com/assets/15685960/12479630/167a98e4-c045-11e5-8b79-04ee664ef2ec.png)

**Comment by muffinresearch** [comment] 2016-01-21 12:10
@ValentinaPC I can't reproduce the same issues. Can you check the STR and make sure that page is the one generating the errors.

Similarly can you check -dev and see if that has the same problem as it might have a more up-to-date config.

**Comment by muffinresearch** [comment] 2016-01-21 14:23
I can repro this on FF 43.0.4 on windows 10. Seems to be CSP blocking the image loads in link elements: e.g:

```html
<link rel="prefetch" href="https://addons-dev-cdn.allizom.org/user-media/previews/full/0/846.png?modified=1331247702">
```

Looks to be a platform bug in FF for windows only. 

It to be fixed in 45.0.a2 (dev edition) but not in 44.0 Beta Update channel. I will see if there's a relevant bug related to this somewhere.

We'd need to look at what the impact on this might be. I suspect that if image prefetching was blocked by CSP it might not cause many problems other than possibly some impact on performance.

**Comment by muffinresearch** [comment] 2016-01-21 14:49
Fwiw I tried adding a hint attribute `as="image"` but it didn't make any difference.

**Comment by muffinresearch** [comment] 2016-01-21 14:50
We're probably going to turn-off report-only on -dev tomorrow. I'm thinking we should test this there and see if there's any noticeable impact.

**Comment by muffinresearch** [comment] 2016-01-22 13:15
Turns out this isn't windows specific. I had prefetch turned off on osx.

**Comment by muffinresearch** [comment] 2016-01-22 14:04
Since CSP is going to block all the pre-fetching it seem like it will be a plan to remove it. I'm also going to look into if a platform bug exists for this and make a test-case.

**Closed** 2016-01-22 16:26 UTC

**Comment by muffinresearch** [comment] 2016-01-22 17:01
There is a bit of a delay because the images are now requested when you open the image carousel. But this is a trade-off. If we can find a better solution as a workaround for the CSP violation we can always add this back.
