### ISSUE TITLE
Validation for a webextension never completes with the unlisted option selected

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1003] opened 2015-11-30 23:53 UTC
## steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/developers/addon/submit/2
2. Select the checkbox 'Do not list my add-on on this site (beta)'
3. Upload a valid webextension file like https://www.dropbox.com/s/at0pdlxpdt1m249/sort-test.xpi?dl=0
4. Wait for validation to complete

## expected behavior:
Validator throws an error saying "Webextensions cannot be unlisted"

##actual behavior:
Validation never completes.

**Comment by magopian** [comment] 2015-12-01 09:36
I can't reproduce the issue, even if I check the 'Do not list my add-on on this site (beta)' checkbox, the validation completes (we do accept unlisted WebExtensions), with the add-on you provided:

<img width="730" alt="screen shot 2015-12-01 at 10 36 55" src="https://cloud.githubusercontent.com/assets/167767/11497157/674b5dc2-9817-11e5-8ba3-ddab11530f40.png">

I'm closing this bug for now, please reopen if you can confirm it still fails for you.

**Comment by ValentinaPC** [comment] 2015-12-03 14:44
I've checked the webextension above in AMO-dev using FF42(Win 7), and the submission was with success even if I've checked the "unlisted" option. 
I've also tried adding a new version, more new files, all with success.
Please see the screenshot:
![2015-12-03_1447](https://cloud.githubusercontent.com/assets/15685960/11562515/0426855c-99d7-11e5-8268-e274b81e12f9.png)

**Comment by ValentinaPC** [comment] 2015-12-10 13:07
The issue is happening again for listed/unlisted add-ons.
I am on AMO-dev and trying to submit a web-extension but the validation process does not complete.
Please see the screenshot: 
![2015-12-10_1458](https://cloud.githubusercontent.com/assets/15685960/11716029/8ce3936c-9f4f-11e5-84be-9a918c237a7a.png)
Attaching the used add-on. (I've changed the .xpi extension to zip, to be able to upload it)
[sort-test-webext.zip](https://github.com/mozilla/olympia/files/58088/sort-test-webext.zip)

**Comment by magopian** [comment] 2016-01-05 11:34
I'm pretty sure this is related to the issues we've been experiencing while uploading add-ons, not webextensions.

Please reopen if I'm wrong.

**Closed by magopian** 2016-01-05 11:34 UTC
Labels: WebExtensions
