### ISSUE TITLE
Changes are not saved in "Account Settings" page if accessed from My Profile -> Manage user

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1170] opened 2016-01-04 14:58 UTC
Steps to reproduce:
1. Log in to AMO-dev page https://addons-dev.allizom.org/en-US/firefox
2. Go to "Username"->My Profile->Manage user
3. Make a change and click "Update Account" blue button

Expected results:
The changes are saved.

Actual results:
The changes are not saved. 

Notes/Issues:
If the "Account Settings" page is accessed directly from the menu, the changes are saved and a "Profile updated" message is displayed on top of the page.
Verified on FF43(Win 7). Issue is reproducing on AMO-dev
Screencast for this issue: http://screencast.com/t/J9jquTLwexvj

**Comment by wagnerand** [comment] 2016-01-04 15:11
https://sentry.prod.mozaws.net/operations/olympia-dev/group/161890/

**Comment by andymckay** [comment] 2016-01-04 18:20
Since its on -dev, possibly related to FxA?

**Comment by mstriemer** [comment] 2016-01-04 19:38
This is actually the admin edit user form but it is being used to edit the currently logged in user. I'm not sure if that's a valid use case or not but it is currently allowed. The form isn't actually submitted because the "Admin log" field hasn't been filled out so this is working as intended. That being said the other required fields are marked as `required` so it is clear that they should be filled in.

Once you fill in the Admin log field you get the Sentry error but that is unrelated to the screencast.

**Comment by mstriemer** [comment] 2016-01-04 19:42
I submitted https://github.com/mozilla/olympia/pull/1171 to mark the `admin_log` field as required. 

I'm not sure what's up with the error. I filed https://github.com/mozilla/olympia/issues/1172 to fix it.

**Comment by magopian** [comment] 2016-01-06 11:06
Looks good, thanks! Do we want a test for this specific use case?
r+wc

**Closed** 2016-01-08 19:20 UTC
Labels: pull-request-ready
