### ISSUE TITLE
Issues at log in with a new created account in AMO-prod

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#917] opened 2015-11-13 09:00 UTC
Steps to reproduce:
1. Load AMO-prod page https://addons.mozilla.org/en-US/firefox
2. Click "Register" link and register as a new user
3. Go to your email and click the confirmation link
4. Try to sign in with the new created account

Expected results:
The message "Successfully verified" is listed in AMO page. After entering the new created email and password the user is logged in.

Actual result:
User cannot log in. An error message is displayed.

Notes/Issues:
Verified on FF42(Win 7). Issue is reproducing on AMO-prod.
Please see the screencast: http://screencast.com/t/nSBAQt540UJ

**Comment by muffinresearch** [comment] 2015-11-13 12:08
The MOC has been notified there's lots of sentry errors with:

```
OperationalError: (1290, 'The MySQL server is running with the --read-only option so it cannot execute this statement')
```
Moc bug is: https://bugzilla.mozilla.org/show_bug.cgi?id=1224527

**Comment by ValentinaPC** [comment] 2015-11-13 12:25
After, some time I was able to log in with the created account.
Now:
-> if I try to delete the newly created account, I receive the message "Profile deleted" but I can log with the that account again. 
-> if, being logged in, I access the "Account Settings" page I see that the "deleted" account became "Anonymous-xxxxxx".
Please see the screencast: http://screencast.com/t/N25th5Qr

**Comment by muffinresearch** [comment] 2015-11-13 12:38
So this sounds like a possible dupe of #913

**Closed** 2015-11-13 12:46 UTC
Labels: bug, duplicate, High Priority
