### ISSUE TITLE
Compat validation page throws in console, doesn't show results

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/olympia#1393] opened 2016-01-14 21:29 UTC
I was looking at the results of the bulk validation run, but I couldn't open any of the validation results pages, like this one: https://addons.mozilla.org/developers/addon/super-drag/validation-result/491597

The throbber is just stuck and nothing shows up. The console shows this error:

`Error: Syntax error, unrecognized expression: <div class="result">`
`      <div class="result-header">`
`        <h4></h4>`
`                <div class="result-summary">.</div>`
`      </div>`
`      <div class="tier-results ajax-loading" data-tier="1"></div>`
`    </div>`

This seems to be a regression and it's blocking sending compat emails to developers, which needs to happen next week at the latest.

**Comment by andymckay** [comment] 2016-01-15 00:02
Tracking #995

**Comment by magopian** [comment] 2016-01-15 08:01
I don't think it's related to #995, but more to #1197 (maybe). I'm going to investigate asap

**Comment by muffinresearch** [comment] 2016-01-15 11:05
We did some debugging and magopian reproduced this on prod using Charles proxy. The relevant line is this one: https://github.com/mozilla/olympia/blob/d8aef0b88a5fd20d4413a37807e9ae79c7602fa8/static/js/zamboni/validator.js#L61

Sizzle blows up because the html has whitespace. Interesting this is fixed in the newer jquery but we can do a temporary 1 line patch to fix it until then.

**Comment by muffinresearch** [comment] 2016-01-15 11:09
This is the relevant rev if a cherry-pick on the current tag is needed: https://github.com/mozilla/olympia/commit/3d5a07bdefb7931b149889e998e4045cb77ceb5d

**Comment by andymckay** [comment] 2016-01-15 20:15
We tested this on stage at https://addons.allizom.org/en-US/developers/addon/image-assistant/validation-result/348194 and we still got the same error, so we haven't pushed.

**Comment by magopian** [comment] 2016-01-15 21:53
Did you do a refresh on the page to get the new JS? I've just tested again and here's what I have:

<img width="971" alt="screen shot 2016-01-15 at 22 52 18" src="https://cloud.githubusercontent.com/assets/167767/12366315/af8522c6-bbda-11e5-966d-574c36bd8ff5.png">

You'll see a bunch of csp *reports* in the console, but those aren't blocking anything and are expected (the CSP stuff isn't tagged yet). Also, the error message from this issue shouldn't be there at all (at least it isn't for me ;)

**Comment by jvillalobos** [comment] 2016-01-15 22:00
I did a hard refresh when testing before and still had problems. Now it's working like magopian posted.

**Comment by muffinresearch** [comment] 2016-01-20 10:58
So I think we're saying this is fixed? FWIW,  the new jquery due for release this week looked have a fix for whitespace issues.

Please re-open if there's any further issues.

**Closed by muffinresearch** 2016-01-20 10:58 UTC

**Comment by jvillalobos** [comment] 2016-01-20 14:52
Yes, I can confirm this was fixed.
