### ISSUE TITLE
List applications and signing status for an add-on

### ISSUE THREAD

**Issue by darktrojan** [mozilla/olympia#989] opened 2015-11-26 22:00 UTC
I was trying out the API upload-and-sign process, and uploaded [this addon](https://addons.mozilla.org/en-US/developers/addon/restart1/edit). The upload completed, and I received the email saying `Your add-on, Restart 4, has passed our automatic tests and is now signed …`. But it is not signed.

This was a few days ago. I just now checked the status-check endpoint and got this message: `{"detail": "User has not read developer agreement."}` which might explain what's going on.

**Comment by andymckay-limited-access** [comment] 2015-11-26 22:01
That's curious, there's no way you should be able to get that far if you have not read the developer agreement.

**Comment by andymckay-limited-access** [comment] 2015-11-26 22:02
https://github.com/mozilla/olympia/blob/master/apps/api/jwt_auth/views.py#L41-L43 means that JWT authentication should fail.

**Comment by darktrojan** [comment] 2015-11-26 22:02
Indeed, and how am I supposed to read it if I'm using the API?

**Comment by darktrojan** [comment] 2015-11-26 22:47
User agreement aside, I wonder if this could be caused by the install.rdf targetApplication being set to `toolkit@mozilla.org`. Is signing dependent on the application?

I added the Firefox identifier and uploaded again and this version *was* signed, so it seems plausible.

**Comment by andymckay** [comment] 2015-11-26 23:47
Yes, thank you for investigating. That's the cause. We only sign for applications that need signing. This has tripped me up more than once and its annoying I didn't think of it sooner. We need a much better way of surfacing this in the API and in the developer hub. 

Based on your last comment, I'd like to alter the bug to reflect that.

**Comment by zeird** [comment] 2015-12-01 00:04
Hi!
I started using Signing API today, created JWT keys, uploaded my `.xpi`-file via API, it got signed (I received an e-mail) for real (I can install it from AMO), checked it's status via API and have tried to download signed `.xpi`-file via API from `files[0].download_url` link, but for reason unknown server keeps responding with `{"detail": "User has not read developer agreement."}` instead of binary file or mirror header.

All 3 `targetApplication` in my `install.rdf` (for FF, SeaMonkey and Fennec) are ok.

I'm not sure if this is the right place to tell about my issue, but this page is the only link that internet search engines return to `detail "User has not read developer agreement."` search query.

**Comment by kumar303** [comment] 2015-12-02 19:16
@zeird does this happen consistently? Or only intermittently?

If it's intermittent it could be related to known cache issues that we're still trying to resolve. https://github.com/mozilla/olympia/issues/977

**Comment by zeird** [comment] 2015-12-02 20:46
@kumar303 two days ago I failed to download my signed `.xpi` with ` {"detail": "User has not read developer agreement."}` error, but today with the same error I failed even to upload my unsigned `.xpi` via API.

Then you won't believe me what happened. I thought "what if the error message does really mean what it says?", and when I tried to "Manage API Keys", AMO asked me to accept developer agreement, for the second time, despite me already having JWT-secret.

So it looks like for whatever reason AMO revoked my developer agreement acceptance and then API naturally showed me a legit "User has not read developer agreement." error message.

Does it look like it has something to do with a cache?

**Comment by kumar303** [comment] 2015-12-03 16:20
Huh, weird. There aren't any caching issues (we know of) that would span more than 10-15 minutes of stale results.

**Comment by zeird** [comment] 2015-12-03 16:25
No, I mean could my developer agreement acceptance revocation be related to cache issues?

**Comment by kumar303** [comment] 2015-12-03 17:09
It seems unlikely to be cache related considering how you described the behavior. It's unexpected though; I can't come up with a theory.

**Comment by andymckay** [comment] 2015-12-03 18:08
@zeird what is the email for your account on AMO, wouldn't mind looking it up. You can email me if you'd rather not put in a public bug at amckay@mozilla.com

**Comment by zeird** [comment] 2015-12-03 18:14
@andymckay the email for my AMO account is l1aqus@gmail.com

**Comment by andymckay** [comment] 2015-12-21 21:02
I think this is a dupe of #1096, since we have someone planning to work on that. I'm going to close this in favour of that one.

**Closed by andymckay** 2015-12-21 21:02 UTC
Labels: API, AWS
