### ISSUE TITLE
[CSP] Possibly allow Google Translate

### ISSUE THREAD

**Issue by marumari** [mozilla/olympia#1590] opened 2016-02-02 16:38 UTC
Relates to #995.

It seems a decent number of our CSP reports come from Google Translate.  See kibana search: `blocked-uri:*translate*`

It's entirely up to us whether or not we want to exempt certain sources, injected by add-ons, in AMO. I don't think we generally want to be in the business of deciding which add-ons get to inject code into AMO, but given how common Google Translate is, we may want to make an exception here.

`connect-src https://translate.googleapis.com`
`frame-src https://translate.google.com`
`img-src https://*.gstatic.com`  (we currently just allow ssl.gstatic.com)
`script-src https://translate.googleapis.com`

Either way, I figured we should have an issue tracking this for reference purposes

**Comment by marumari** [comment] 2016-02-02 16:43
Just fyi, as an alternative to `https://*.gstatic.com`, we could instead simply add `https://www.gstatic.com`, since that's where the img-src violations are originating from.

**Comment by jvehent** [comment] 2016-02-02 16:55
As I understand it, this is caused by addons automatically translating pages using google translate. When those addons attempt to translate an AMO page, a violation is triggered.
Those addons are probably broken on any sites that have CSP disallowing the google translate domains. Fixing our policy does not change this.

I'm not convinced that we should allow _random_ sites to accommodate addons. Google translate is one example, and there probably will be more of them in the future. In my opinion, the question is "how many users are we currently breaking, and is it low enough to be acceptable?".

cc @dveditz & @andymckay

**Comment by andymckay** [comment] 2016-02-02 17:21
@marumari I can't seem to get any numbers back from Kibana, am I doing it wrong. Can you tell us roughly how many a day?

We provide localisations on AMO, they aren't perfect so I can see people needing to translate the pages, but the numbers always get small. There are a few translator add-ons on AMO, the biggest having 820k users.

It does feel like if we allow certain sites we water down the value of CSP, because each time we allow that we are implicitly trusting that site.

**Comment by marumari** [comment] 2016-02-02 17:30
According to Kibana, I see 119,149 violations over the last 24h, or about 80 per minute.  This accounts for ~3% of our current CSP violations, but it will probably be much higher once the fix for services.addons.mozilla.org goes in.

Note: I also updated all the sources we would have to add in the initial bug.  Upon further investigation, it looks like we'd need to add four directives, not two.  :disappointed:

**Comment by andymckay** [comment] 2016-02-02 20:28
After thinking about this i'm -1 on this proposal. It means we have to have a policy about allowing such add-ons on AMO (which is work). I would much rather invest time with the add-ons authors and CSP experts to see if we can get them working in a way that makes sense. That's good not just for AMO, but the web in general.

**Comment by deadsquid** [comment] 2016-02-02 20:31
What Andy said. I'd like to look at a best practices solution for add-on development first. I can see the policy and list management overhead being something we really shouldn't be managing (and being potentially very complex).

**Comment by andymckay** [comment] 2016-02-03 15:26
Closing based on last couple of comments.

**Closed by andymckay** 2016-02-03 15:26 UTC
