### ISSUE TITLE
Adding a new version for an unlisted add-on never completes validation

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1016] opened 2015-12-02 04:53 UTC
## steps to reproduce:
1. Load https://addons.allizom.org/en-US/developers/addon/testing-amor-stuff1/versions
2. Upload a new version for this unlisted add-on

## observed behavior:
Validation never completes

## screenshot
https://www.dropbox.com/s/tcp4l9s7bs69dpn/Screenshot%202015-12-01%2020.53.29.png?dl=0

**Comment by magopian** [comment] 2015-12-02 09:46
This is really weird, second time you're experiencing a timeout that I can't reproduce:

<img width="467" alt="screen shot 2015-12-02 at 10 44 25" src="https://cloud.githubusercontent.com/assets/167767/11527523/d10b1c28-98e1-11e5-9eea-2db597dfef02.png">
<img width="724" alt="screen shot 2015-12-02 at 10 45 10" src="https://cloud.githubusercontent.com/assets/167767/11527524/d10ed2aa-98e1-11e5-9d20-dfbc8e23b082.png">

If there is an issue, I believe it's not linked to webextensions.

**Comment by ValentinaPC** [comment] 2015-12-02 17:00
I could also reproduce this issue (intermittently) when uploading a new file for a current or old add-on version.
Please see the screenshot: 
![2015-12-02_1847](https://cloud.githubusercontent.com/assets/15685960/11537451/b64066de-9925-11e5-82a3-e96c66ee8ec5.png)

**Comment by kumar303** [comment] 2015-12-02 17:31
I've seen this same thing when testing signing through the API on stage (last week and the week before). The validation *sometimes* never completes. It looked as if the celery task to run validation was never started. I couldn't confirm this though and Jason and I found no connection errors. Just a theory.

**Comment by andymckay** [comment] 2015-12-02 21:13
@jasonthomas is going to send over some detail of extra queues have been created.

**Comment by kumar303** [comment] 2015-12-22 18:22
Just for cross-reference, https://github.com/mozilla/olympia/issues/1124 is an error that would cause validation to never complete

**Comment by andymckay** [comment] 2016-01-07 19:17
We think this is #1229 and is being tracked on #1244, due to the large number of similar bugs on this I'm closing this one.

**Closed by andymckay** 2016-01-07 19:17 UTC
Labels: AWS
