### ISSUE TITLE
[traceback] django.db.models.fields.related in __get__  DoesNotExist: Addon has no persona.

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1619] opened 2016-02-04 18:58 UTC
## steps to reproduce:
1. Load  https://addons.mozilla.org/fa/firefox/addon/bb-8-theme

## sentry:
https://sentry.prod.mozaws.net/operations/olympia-prod/group/151490/

## traceback details:
Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "addons/decorators.py", line 43, in wrapper
    return f(request, addon, *args, **kw)
  File "addons/views.py", line 86, in addon_detail
    return persona_detail(request, addon)
  File "mobility/decorators.py", line 23, in wrapper
    return f(request, *args, **kw)
  File "addons/views.py", line 168, in persona_detail
    persona = addon.persona
  File "django/db/models/fields/related.py", line 206, in __get__
    self.related.get_accessor_name()))

**Comment by andymckay** [comment] 2016-02-05 23:06
Dupe of #1282.

**Closed by andymckay** 2016-02-05 23:06 UTC
