### ISSUE TITLE
"Themes-Newest" page returns a 500 error 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1040] opened 2015-12-03 16:42 UTC
Steps to reproduce:
1. Load AMO-stage https://addons.allizom.org/en-US/firefox
2. Click "Themes"-"Newest" option

Expected results:
Newest themes are listed.

Actual results:
"Oops!" page is displayed.

Notes/Issues:
Issue is also reproducing on Android.
Verified on FF42(Win 7, Android 4.2.1). Issue is only reproducing on AMO-stage.
Screencast for this issue: http://screencast.com/t/4U3yV6I9r

**Comment by andymckay** [comment] 2015-12-03 17:53
We think this was caused by #1036, when we reverted that change it worked. I think when we fix up #1036, this won't be an issue. Going to close this in favor of that bug.

**Closed by andymckay** 2015-12-03 17:53 UTC

**Comment by ValentinaPC** [comment] 2015-12-08 14:35
Verified as fixed on AMO-stage.
Postfix screenshot:
![2015-12-08_1620](https://cloud.githubusercontent.com/assets/15685960/11658102/924c4d94-9dc9-11e5-9039-a37344571f5f.png)
