### ISSUE TITLE
Review Points System deducting

### ISSUE THREAD

**Issue by erosman** [mozilla/olympia#1554] opened 2016-01-30 14:06 UTC
There has been a long-standing bug (2015-09-18): [Review Points System deducting](https://bugzilla.mozilla.org/show_bug.cgi?id=1205986)
It keeps on happening and just happened again now.
I processed a single **Moderated Reviews**, 1 point was added and 60 points deducted.

!!??

**Comment by jvillalobos** [comment] 2016-01-30 15:52
Closing since it's a dupe of 1205986

**Closed by jvillalobos** 2016-01-30 15:52 UTC

**Comment by erosman** [comment] 2016-01-30 16:32
I wondered if it would get more attention here since nothing has happened with buzilla filing...

- I was told by Andreas that developers no longer check the bugzilla and concentrate on github issues
- It has already been 4.5 months and it hasn't been fixed

**Comment by wagnerand** [comment] 2016-01-30 17:00
I don't remember saying that developers no longer check bugzilla.

They still do.

**Comment by erosman** [comment] 2016-01-30 17:15
> I don't remember saying that developers no longer check bugzilla.

I do remember.. on IRC
I posted a bug to bugzilla and you said that I should post it to github instead since developers don't check bugzilla

**Comment by wagnerand** [comment] 2016-01-30 19:21
I don't think I said that. Either way it is true that developers prefer
GitHub issues, but people are still filing bugzilla bugs, because they
might not know that we opened GitHub issue submission. Therefore, we cannot
just abandon bugzilla. But just because there has been no movement on a bug
(or an issue) does not mean no one has looked at it. It's just a matter of
priorizitation.
