### ISSUE TITLE
'Manage user' button on user profile page is broken

### ISSUE THREAD

**Issue by wagnerand** [mozilla/olympia#1022] opened 2015-12-02 17:42 UTC
For admins, there is a "Manage user" button on every user profile page, for example https://addons.mozilla.org/en-US/firefox/user/herr-sonntag/

That button links to `https://addons.mozilla.org/de/firefox/users/edit/1` which is a 404. It should be `https://addons.mozilla.org/de/firefox/users/edit/3787896`
(Note that the "Report user" button has the correct id and therefore works.)

**Comment by jvillalobos** [comment] 2015-12-02 19:04
This is a dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1226378

**Comment by wagnerand** [comment] 2015-12-02 19:37
But the linked PR https://github.com/mozilla/olympia/pull/960 has never been merged, or am I missing something, @andymckay?

**Comment by madalincm** [comment] 2015-12-03 15:07
The issue is still reproducing in addons-dev.allizom.org
Please view this screencast: http://screencast.com/t/oGmdj2j6lp

**Comment by madalincm** [comment] 2015-12-03 15:11
Oups wrong bug. That comment was for #1020 

The manage button is working in -dev and stage (I can't verify production) but the content of that page is still broken.

**Comment by andymckay** [comment] 2015-12-03 16:30
Fixed now, there were problems with the deploy.

**Closed by andymckay** 2015-12-03 16:30 UTC
Labels: needs qa

**Comment by ValentinaPC** [comment] 2015-12-10 08:32
Verified as fixed on AMO-dev FF42(Win 7).
Postfix screencast: http://screencast.com/t/N0K5c9jYywhr
