### ISSUE TITLE
AMO prod is intermittently down

### ISSUE THREAD

**Issue by vcarciu** [mozilla/olympia#903] opened 2015-11-11 16:23 UTC
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Load AMO prod

Expected results:
AMO prod is correctly loaded

Actual results:
Sometimes, AMO prod is not loading and it is returning a 503 or 502 Bad Gateway 

Screencast :  http://screencast.com/t/m0Foplvl39QJ

**Comment by wagnerand** [comment] 2015-11-11 16:27
Dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1223795

**Closed** 2015-11-12 23:05 UTC
Labels: verified-fixed
